In [ ]:
import pandas as pd
import numpy as np
import openpyxl

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

In [ ]:
s2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s2)

In [ ]:
s3 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})
print(s3)

In [ ]:
s4 = pd.Series(np.arange(10, 20))
print(s4)

In [ ]:
s5 = pd.Series(5.0, index=['x', 'y', 'z'])
print(s5)

In [ ]:
s6 = pd.Series([1, 2, 3], dtype=np.float32, name='scores')
print(s6)

In [ ]:
s = pd.Series({'Krish':1, 'Ravi':2, 'Jay':3, 'Kishan':4, 'Nirav':5})
print(s)

In [ ]:
print(s.index)
print(s.values)
print(s.dtype)
print(s.size)
print(s.name)
print(s.shape)
print(s.ndim)
print(s.is_unique)

In [ ]:
print(s['Krish'])
print(s[['Krish', 'Nirav']])

In [ ]:
print(s.iloc[0]) 
print(s.iloc[-1]) 
print(s.iloc[1:4])

In [ ]:
print(s.loc['Krish':'Nirav'])

In [ ]:
print(s[s > 80])  
print(s[s.between(80, 90)])

In [ ]:
s = pd.Series([10, 20, 30, 40, 50])

In [ ]:
print(s + 5) 
print(s * 2) 
print(s ** 2)

In [ ]:
print(s.sum()) 
print(s.mean())
print(s.median())
print(s.std())
print(s.min()) 
print(s.max())
print(s.describe())

In [ ]:
a = pd.Series({'x':1, 'y':2, 'z':3})
b = pd.Series({'y':10, 'z':20, 'w':30})
print(a + b)

In [ ]:
grades = pd.Series(['A','B','A','C','B','A','D'])
print(grades.value_counts())

In [ ]:
s.apply(lambda x: x * 2 if x > 25 else x)

In [6]:
df = pd.DataFrame({
    'Name'  : ['Alice', 'Bob', 'Carol', 'Dave', 'Eve'],
    'Age'   : [28, 34, 29, 42, 31],
    'City'  : ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', 'Pune'],
    'Salary': [85000, 72000, 91000, 105000, 68000],
    'Dept'  : ['Engineering','Marketing','Engineering','Management','Marketing']
})

In [7]:
df2 = pd.DataFrame([
    {'Name':'Alice', 'Score':92, 'Pass':True},
    {'Name':'Bob',   'Score':74, 'Pass':True},
    {'Name':'Carol', 'Score':45, 'Pass':False}
])

In [8]:
arr = np.random.rand(4, 3)
df3 = pd.DataFrame(arr, columns=['A','B','C'])

In [9]:
df4 = pd.DataFrame({
    'Revenue': pd.Series([100,200,150], index=['Jan','Feb','Mar']),
    'Costs'  : pd.Series([80,160,110],  index=['Jan','Feb','Mar'])
})

In [10]:
df5 = pd.DataFrame({'Score':[90,85,78]},
                    index=['Alice','Bob','Carol'])

In [11]:
df_empty = pd.DataFrame(columns=['Name','Score','Grade'])

In [12]:
df.head()

    Name  Age       City  Salary         Dept
0  Alice   28     Mumbai   85000  Engineering
1    Bob   34      Delhi   72000    Marketing
2  Carol   29  Bangalore   91000  Engineering
3   Dave   42     Mumbai  105000   Management
4    Eve   31       Pune   68000    Marketing

In [13]:
df.head(3)

    Name  Age       City  Salary         Dept
0  Alice   28     Mumbai   85000  Engineering
1    Bob   34      Delhi   72000    Marketing
2  Carol   29  Bangalore   91000  Engineering

In [14]:
df.tail(2)

   Name  Age    City  Salary        Dept
3  Dave   42  Mumbai  105000  Management
4   Eve   31    Pune   68000   Marketing

In [15]:
df.sample(3)

    Name  Age       City  Salary         Dept
0  Alice   28     Mumbai   85000  Engineering
3   Dave   42     Mumbai  105000   Management
2  Carol   29  Bangalore   91000  Engineering

In [16]:
df.shape

(5, 5)

In [18]:
len(df)

5

In [19]:
df.size

25

In [20]:
df.ndim

2

In [21]:
df.columns

Index(['Name', 'Age', 'City', 'Salary', 'Dept'], dtype='str')

In [22]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [23]:
df.dtypes

Name        str
Age       int64
City        str
Salary    int64
Dept        str
dtype: object

In [24]:
df.info

<bound method DataFrame.info of     Name  Age       City  Salary         Dept
0  Alice   28     Mumbai   85000  Engineering
1    Bob   34      Delhi   72000    Marketing
2  Carol   29  Bangalore   91000  Engineering
3   Dave   42     Mumbai  105000   Management
4    Eve   31       Pune   68000    Marketing>

In [25]:
df.describe

<bound method NDFrame.describe of     Name  Age       City  Salary         Dept
0  Alice   28     Mumbai   85000  Engineering
1    Bob   34      Delhi   72000    Marketing
2  Carol   29  Bangalore   91000  Engineering
3   Dave   42     Mumbai  105000   Management
4    Eve   31       Pune   68000    Marketing>

In [26]:
df.describe(include='all')

         Name        Age    City       Salary         Dept
count       5   5.000000       5       5.0000            5
unique      5        NaN       4          NaN            3
top     Alice        NaN  Mumbai          NaN  Engineering
freq        1        NaN       2          NaN            2
mean      NaN  32.800000     NaN   84200.0000          NaN
std       NaN   5.630275     NaN   14923.1364          NaN
min       NaN  28.000000     NaN   68000.0000          NaN
25%       NaN  29.000000     NaN   72000.0000          NaN
50%       NaN  31.000000     NaN   85000.0000          NaN
75%       NaN  34.000000     NaN   91000.0000          NaN
max       NaN  42.000000     NaN  105000.0000          NaN

In [27]:
df.describe(include='object')

/var/folders/0_/2bhgd9f11mzgc8xc4h4crf2r0000gn/T/ipykernel_29096/4084012645.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

         Name    City         Dept
count       5       5            5
unique      5       4            3
top     Alice  Mumbai  Engineering
freq        1       2            2

In [28]:
df.describe(percentiles=[.1, .25, .5, .75, .9])

             Age       Salary
count   5.000000       5.0000
mean   32.800000   84200.0000
std     5.630275   14923.1364
min    28.000000   68000.0000
10%    28.400000   69600.0000
25%    29.000000   72000.0000
50%    31.000000   85000.0000
75%    34.000000   91000.0000
90%    38.800000   99400.0000
max    42.000000  105000.0000

In [29]:
df_miss = pd.DataFrame({
    'Name'  : ['Alice', 'Bob', None, 'Dave'],
    'Age'   : [28, None, 29, 42],
    'Salary': [85000, 72000, None, None]
})

In [30]:
df_miss.isnull()
df_miss.isnull().sum()
df_miss.notnull().sum()
df_miss.isna().sum()

Name      1
Age       1
Salary    2
dtype: int64

In [31]:
df_miss.isnull().sum().sum()

np.int64(4)

In [32]:
df_miss.isnull().mean() * 100

Name      25.0
Age       25.0
Salary    50.0
dtype: float64

In [34]:
try:
    df = pd.read_csv('employees.csv')

except FileNotFoundError:
    print("File not found. Please check the file path and name.")

File not found. Please check the file path and name.

In [36]:
df = pd.read_csv('employees.csv')

In [40]:
print(f"Shape: {df.shape}")
df.info()
df.head()

Shape: (5, 3)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5 non-null      int64
 1   Name    5 non-null      str
 2   Role    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

   ID     Name            Role
0   1    Krish        AI Engg.
1   2   Satyam          Editor
2   3   Dhiren  Ethical Hacker
3   4    Shubh          Editor
4   5  Atharva              CA

In [45]:
df.to_csv('output.csv', index=False)

In [48]:
df.to_excel('output.xlsx', sheet_name='Results', index=False)

In [49]:
with pd.ExcelWriter('report.xlsx') as writer:
    df.to_excel(writer, sheet_name='Employees', index=False)
    df2.to_excel(writer, sheet_name='Summary', index=False)

In [54]:
df.to_json('output.json', orient='records', indent=2)

In [55]:
df

   ID     Name            Role
0   1    Krish        AI Engg.
1   2   Satyam          Editor
2   3   Dhiren  Ethical Hacker
3   4    Shubh          Editor
4   5  Atharva              CA